### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by michelebonapace** [michelebonapace/RitardoAutobus#1]
Come utente voglio poter fare login all'interno del sito

HTD: nella home del sito deve esserci il tasto login, che apre la form di login

**Comment by CarbonaraJack** [comment]
Piccolo problemino
![schermata del 2017-11-24 09-36-33](https://user-images.githubusercontent.com/10898872/33202050-3f35aada-d0fb-11e7-9bbb-79084027925c.png)

**Comment by CarbonaraJack** [comment]
risolto cambiando la porta da 7777 a 8080
