### ISSUE TITLE
Segnalazione ritardi

### ISSUE THREAD

**Issue by michelebonapace** [michelebonapace/RitardoAutobus#3]
Come utente voglio poter segnalare i ritardi

HTD: ci deve essere un menu dove cliccando il tasto segnala ritardo, segnalo il ritardo di un autobus (senza bisogno di inserire la posizione e l'orario)

**Comment by CarbonaraJack** [comment]
Il backend deve inserire nel database il ritardo passato dal frontend

**Comment by CarbonaraJack** [comment]
La struttura nel backend è pronta, attendo i dati corretti per poter completare la task.
Per avere i dati corretti devo fornirne in altre task, quindi rimetto questa task on hold

**Comment by CarbonaraJack** [comment]
Completo
