### ISSUE TITLE
Visione delle fermate vicine

### ISSUE THREAD

**Issue by SZamboni** [michelebonapace/RitardoAutobus#36]
Una volta che l'utente apre l'app deve poter selezionare le fermate più vicine a lui.

HTD: l'utente deve vedere una mappa con segnalate le fermate più vicine. Inoltre sotto alla mappa dovrebbe apparire una lista cliccabile con le fermate.

**Comment by CarbonaraJack** [comment]
Il backend si deve occupare di restituire una lista delle fermate più vicine in risposta ad una richiesta del frontend contenente le coordinate gps dell'utente

**Comment by CarbonaraJack** [comment]
Il lato backend è completo. Il frontend deve occuparsi di salvare i dati riferiti dal backend in modo da fornirli alle query successive

**Comment by CarbonaraJack** [comment]
Completo. Le fermate vengono visualizzate sia sulla mappa che in una lista al di sotto.
