### ISSUE TITLE
Ricerca ritardi

### ISSUE THREAD

**Issue by SZamboni** [michelebonapace/RitardoAutobus#37]
Un utente deve poter sapere l'orario esatto degli autobus una volta che seleziona una fermata

HTD: come utente una volta che clicco su una fermata devo poter visionare il primo orario in cui passerà ogni linea presso quella fermata

**Comment by CarbonaraJack** [comment]
Il backend deve rispondere alla richiesta del frontend inviando i dati relativi alla fermata

**Comment by CarbonaraJack** [comment]
Lato backend completo
