### ISSUE TITLE
Integrazione dati trentino trasporti in un database di appoggio (REVERSE ENGINEERING)

### ISSUE THREAD

**Issue by michelebonapace** [michelebonapace/RitardoAutobus#7]
I dati di trentino trasporti devono essere scaricati e inseriti  nel database di appoggio ("shadow db")
HTD controllare se le open data di trentino trasporti possono essere inserite correttamente nel database e creare un EER diagram del database di appoggio

**Comment by CarbonaraJack** [comment]
C'è un problema con la codifica caratteri.
Bisogna stare attenti agli accenti quando si popola il database partendo da quello di TT.
